name: Build

on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          target: linux-x64
        - os: windows-latest
          target: win-x64
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Build ${{ matrix.target }}
      run: dotnet publish Interface/Interface.csproj -r ${{ matrix.target }} -c release -o "${{ github.workspace }}/builds/${{ matrix.target }}"

    - name: Upload ${{ matrix.target }} Build
      uses: actions/upload-artifact@v3
      with:
        name: Interface-${{ matrix.target }}
        path: ${{ github.workspace }}/builds/${{ matrix.target }}
